/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"

int *suma_1_svc(dupla *argp, struct svc_req *rqstp){
	static int  result;
	result=argp->a+argp->b;
	printf("Peticion Aceptada UwU\n");
	printf("Recibi: \nNumero 1: %d\nNumero 2: %d\n",argp->a,argp->b);
	printf("Respuesta enviada: %d\n",result);
	return &result;
}
